export interface respuestaPactoDireco{
    codigo: string,
    mensajeCliente: string,
    mensajeSistema: string,
    cantidad: string,
    totales: string,
    respActo: pactoDirecto[],
    jornadasList: []
}

export interface pactoDirecto {
    ID_OPER:              string,
    ID_OC:                string,
    PRODUCTO:             string,
    TIPO_NOTIFICACION:    string,
    TIPO_OPER:            string,
    MTO_DIVISAS:          string,
    MTO_BOLIVARES:        string,
    TASA_CAMBIO:          string,
    COD_FINSTITUCION:     string,
    MTO_COMI:             string,
    TIPO_PER_OFER:        string,
    CED_RIF_OFER:         string,
    NOM_OFER:             string,
    CTA_OFER_MN:          string,
    CTA_OFER_ME:          string,
    TIPO_INSTRUM:         string,
    TIPO_PER_DEMA:        string,
    CED_RIF_DEMA:         string,
    NOM_DEMA:             string,
    CTA_DEMA_MN:          string,
    CTA_DEMA_ME:          string,
    FECH_OPER:            string,
    COD_DIVISAS:          string,
    MTO_PACTOBASE:        string,
    MTO_CONTRAVALORBASE:  string,
    TASA_PACTOBASE:       string,
    TIPO_PACTO:           string,
    STATUS_ENVIO:         string,
    FECHA_ENVIO:          string,
    OBSERVACION :         string,
    ID_BCV:               string,
    ID_JORNADA:           string,
    HORA:                 string,
    MTO_CONTRAVALOR_USD:  string
}
