export interface articulo {
     id:any,
    codArticulo: any,
    idTipoArt: any,
    descrTipoArt: any,
    idDescrArt:  any,
    dercripcionArt : any,
    idTipoImpre:any,
    tipoImpresora: any,
    direccionIp: any,
    idDescConsumible: any,
    descConsumible: any,
    modeloConsumible: any,    
    cantidadArt : any,
    unidadVenta : any,
  }