services:
  notinfi-dev:
    image: notinfi-dev:latest
    container_name: notinfi-dev
    ports:
      - "4201:4201"
    environment:
      - CHOKIDAR_USEPOLLING=1
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - stack-net

networks:
  stack-net:
    external: true
