version: '3.8'
services:
  web:
    image: notinfi-dev:lastest
    container_name: notinfi-dev
    ports:
      - "4201:4201"
    environment:
      - CHOKIDAR_USEPOLLING=1
      - NODE_ENV=development
    restart: unless-stopped
